Repository Julio-o-Julio/02-todolist, pull requests merged in 2025-06, with the labels that each got.

#12 docs: criar README.md do projeto explicando a descrição e rodar na máquina local
  README.md
Labels: documentation

#15 feat: Criando rotas de tag-todo
  api/src/routes/tagRoutes.js
Labels: enhancement

#10 feat: Implementado o modal para o gerenciamento das tags de cada tarefa closes #5
  front/src/App.jsx
  front/src/components/ModalAddTag.jsx
  front/src/components/SpanTags.jsx
  front/src/components/Todos.jsx
Labels: enhancement

#14 docs: Implementando as modificações para exibir lista de endpoints da API no log ao iniciar o servidor closes #4
  api/package-lock.json
  api/package.json
  api/src/index.js
Labels: documentation

#20 Arrumando bug no arquivo index.js. Merge Hotfix/v1.0.1 para a branch Develop
  api/.env.exemple
  api/src/index.js
Labels: bug
